//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UdemyProject.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblkulupler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblkulupler()
        {
            this.tblogrencilers = new HashSet<tblogrenciler>();
        }
    
        public byte kulupid { get; set; }
        public string kulupad { get; set; }
        public Nullable<short> kulupkontenjan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblogrenciler> tblogrencilers { get; set; }
    }
}
