//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UdemyProject.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblnotlar
    {
        public int notid { get; set; }
        public Nullable<byte> dersid { get; set; }
        public Nullable<int> ogrid { get; set; }
        public Nullable<byte> sinav1 { get; set; }
        public Nullable<byte> sinav2 { get; set; }
        public Nullable<byte> sinav3 { get; set; }
        public Nullable<byte> proje { get; set; }
        public Nullable<decimal> ortalama { get; set; }
        public Nullable<bool> durum { get; set; }
    
        public virtual tbldersler tbldersler { get; set; }
        public virtual tblogrenciler tblogrenciler { get; set; }
    }
}
