//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UdemyProject.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblogrenciler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblogrenciler()
        {
            this.tblnotlars = new HashSet<tblnotlar>();
        }
    
        public int ogrenciıd { get; set; }
        public string ograd { get; set; }
        public string ogrsoyad { get; set; }
        public string ogrfoto { get; set; }
        public string ogrcinsiyet { get; set; }
        public Nullable<byte> ogrkulup { get; set; }
    
        public virtual tblkulupler tblkulupler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblnotlar> tblnotlars { get; set; }
    }
}
